// Generated by src/stage-assets.ts — do not edit manually.
export const runtimeAssets = {
  "karna.master": "/generated/karna-kavacha-demo/karna_master-karna_master.png",
  "sun.symbol": "/generated/karna-kavacha-demo/sun_symbol-sun_symbol.png",
  "battlefield.001": "/generated/karna-kavacha-demo/battlefield_001-battlefield_001.png",
  "indra.master": "/generated/karna-kavacha-demo/indra_master-indra_master.png",
  "armor.detail": "/generated/karna-kavacha-demo/armor_detail-armor_detail.png"
} as const;
