// Generated by src/stage-assets.ts — do not edit manually.
export const runtimeAssets = {
  "karna": "/generated/karna-full-journey/karna-karna.png",
  "surya_glow": "/generated/karna-full-journey/surya_glow-surya_glow.png",
  "kavach_kundal": "/generated/karna-full-journey/kavach_kundal-kavach_kundal.png",
  "ashwa_river": "/generated/karna-full-journey/ashwa_river-ashwa_river.png",
  "kunti": "/generated/karna-full-journey/kunti-kunti.png",
  "tournament_arena": "/generated/karna-full-journey/tournament_arena-tournament_arena.png",
  "duryodhana": "/generated/karna-full-journey/duryodhana-duryodhana.png",
  "kurukshetra_battlefield": "/generated/karna-full-journey/kurukshetra_battlefield-kurukshetra_battlefield.png",
  "indra": "/generated/karna-full-journey/indra-indra.png"
} as const;
