// Generated by src/align-whisper.ts — do not edit manually.
export const runtimeCaptions: Record<string, Array<{word: string; start: number; end: number; score: number}>> = {
  "B01": [
    {
      "word": "कर्ण",
      "start": 0.04,
      "end": 0.321,
      "score": 0.553
    },
    {
      "word": "की",
      "start": 0.421,
      "end": 0.501,
      "score": 0.828
    },
    {
      "word": "सबसे",
      "start": 0.622,
      "end": 0.983,
      "score": 0.735
    },
    {
      "word": "बड़ी",
      "start": 1.063,
      "end": 1.244,
      "score": 0.271
    },
    {
      "word": "ताकत,",
      "start": 1.344,
      "end": 1.845,
      "score": 0.84
    },
    {
      "word": "वही",
      "start": 2.146,
      "end": 2.347,
      "score": 0.835
    },
    {
      "word": "कवच,",
      "start": 2.427,
      "end": 2.909,
      "score": 0.781
    },
    {
      "word": "जो",
      "start": 3.25,
      "end": 3.33,
      "score": 0.322
    },
    {
      "word": "उसने",
      "start": 3.35,
      "end": 3.651,
      "score": 0.874
    },
    {
      "word": "खुद",
      "start": 3.771,
      "end": 3.952,
      "score": 0.897
    },
    {
      "word": "अपने",
      "start": 3.972,
      "end": 4.213,
      "score": 0.988
    },
    {
      "word": "हाथों",
      "start": 4.293,
      "end": 4.554,
      "score": 0.762
    },
    {
      "word": "से",
      "start": 4.654,
      "end": 4.734,
      "score": 0.763
    },
    {
      "word": "त्याग",
      "start": 4.814,
      "end": 5.035,
      "score": 0.61
    },
    {
      "word": "दिया।",
      "start": 5.115,
      "end": 5.276,
      "score": 0.933
    }
  ],
  "B02": [
    {
      "word": "जन्म",
      "start": 5.629,
      "end": 5.87,
      "score": 0.842
    },
    {
      "word": "से",
      "start": 5.99,
      "end": 6.07,
      "score": 0.927
    },
    {
      "word": "मिला",
      "start": 6.171,
      "end": 6.511,
      "score": 0.948
    },
    {
      "word": "यह",
      "start": 6.852,
      "end": 6.952,
      "score": 0.49
    },
    {
      "word": "दिव्य",
      "start": 7.133,
      "end": 7.433,
      "score": 0.622
    },
    {
      "word": "कवच",
      "start": 7.554,
      "end": 7.975,
      "score": 0.778
    },
    {
      "word": "और",
      "start": 8.175,
      "end": 8.295,
      "score": 0.898
    },
    {
      "word": "कुंडल",
      "start": 8.436,
      "end": 8.797,
      "score": 0.819
    },
    {
      "word": "कर्ण",
      "start": 8.917,
      "end": 9.117,
      "score": 0.62
    },
    {
      "word": "के",
      "start": 9.218,
      "end": 9.278,
      "score": 0.996
    },
    {
      "word": "शरीर",
      "start": 9.398,
      "end": 9.699,
      "score": 0.994
    },
    {
      "word": "से",
      "start": 9.819,
      "end": 9.899,
      "score": 0.788
    },
    {
      "word": "जुड़े",
      "start": 9.999,
      "end": 10.2,
      "score": 0.489
    },
    {
      "word": "थे,",
      "start": 10.3,
      "end": 10.48,
      "score": 0.978
    },
    {
      "word": "और",
      "start": 10.721,
      "end": 10.821,
      "score": 0.742
    },
    {
      "word": "हर",
      "start": 10.962,
      "end": 11.122,
      "score": 0.747
    },
    {
      "word": "शत्रु",
      "start": 11.222,
      "end": 11.523,
      "score": 0.774
    },
    {
      "word": "के",
      "start": 11.583,
      "end": 11.663,
      "score": 0.706
    },
    {
      "word": "वार",
      "start": 11.763,
      "end": 11.984,
      "score": 0.622
    },
    {
      "word": "से",
      "start": 12.084,
      "end": 12.204,
      "score": 0.994
    },
    {
      "word": "उसे",
      "start": 12.345,
      "end": 12.545,
      "score": 0.993
    },
    {
      "word": "सुरक्षित",
      "start": 12.686,
      "end": 13.187,
      "score": 0.686
    },
    {
      "word": "रखते,",
      "start": 13.207,
      "end": 13.588,
      "score": 0.93
    },
    {
      "word": "उसे",
      "start": 13.748,
      "end": 13.989,
      "score": 0.887
    },
    {
      "word": "अजेय",
      "start": 14.089,
      "end": 14.369,
      "score": 0.75
    },
    {
      "word": "बनाते",
      "start": 14.45,
      "end": 14.81,
      "score": 0.911
    },
    {
      "word": "थे।",
      "start": 14.891,
      "end": 14.951,
      "score": 0.722
    }
  ],
  "B03": [
    {
      "word": "यह",
      "start": 15.304,
      "end": 15.504,
      "score": 0.808
    },
    {
      "word": "कवच",
      "start": 15.605,
      "end": 15.865,
      "score": 0.449
    },
    {
      "word": "और",
      "start": 15.965,
      "end": 16.105,
      "score": 0.564
    },
    {
      "word": "कुंडल",
      "start": 16.205,
      "end": 16.606,
      "score": 0.859
    },
    {
      "word": "उसे",
      "start": 16.726,
      "end": 16.946,
      "score": 0.89
    },
    {
      "word": "सूर्यदेव",
      "start": 17.126,
      "end": 17.727,
      "score": 0.73
    },
    {
      "word": "से",
      "start": 17.807,
      "end": 17.907,
      "score": 0.824
    },
    {
      "word": "जन्म",
      "start": 18.068,
      "end": 18.288,
      "score": 0.665
    },
    {
      "word": "के",
      "start": 18.408,
      "end": 18.468,
      "score": 0.827
    },
    {
      "word": "समय",
      "start": 18.628,
      "end": 18.869,
      "score": 0.77
    },
    {
      "word": "ही",
      "start": 18.949,
      "end": 19.029,
      "score": 0.982
    },
    {
      "word": "मिले",
      "start": 19.089,
      "end": 19.329,
      "score": 0.672
    },
    {
      "word": "थे,",
      "start": 19.429,
      "end": 19.59,
      "score": 0.717
    },
    {
      "word": "इसलिए",
      "start": 19.93,
      "end": 20.29,
      "score": 0.717
    },
    {
      "word": "इन्हें",
      "start": 20.371,
      "end": 20.571,
      "score": 0.728
    },
    {
      "word": "खोना",
      "start": 20.691,
      "end": 21.011,
      "score": 0.929
    },
    {
      "word": "उसके",
      "start": 21.111,
      "end": 21.392,
      "score": 0.876
    },
    {
      "word": "जीवन",
      "start": 21.532,
      "end": 21.832,
      "score": 0.748
    },
    {
      "word": "को",
      "start": 21.912,
      "end": 22.053,
      "score": 0.877
    },
    {
      "word": "सीधे",
      "start": 22.153,
      "end": 22.433,
      "score": 0.847
    },
    {
      "word": "जोखिम",
      "start": 22.553,
      "end": 22.854,
      "score": 0.398
    },
    {
      "word": "में",
      "start": 22.934,
      "end": 23.014,
      "score": 0.519
    },
    {
      "word": "डाल",
      "start": 23.114,
      "end": 23.294,
      "score": 0.65
    },
    {
      "word": "सकता",
      "start": 23.354,
      "end": 23.635,
      "score": 0.882
    },
    {
      "word": "था।",
      "start": 23.655,
      "end": 23.695,
      "score": 0.002
    }
  ],
  "B04": [
    {
      "word": "कुरुक्षेत्र",
      "start": 24.045,
      "end": 24.706,
      "score": 0.658
    },
    {
      "word": "का",
      "start": 24.826,
      "end": 24.926,
      "score": 0.732
    },
    {
      "word": "महायुद्ध",
      "start": 24.986,
      "end": 25.607,
      "score": 0.67
    },
    {
      "word": "निकट",
      "start": 25.668,
      "end": 26.048,
      "score": 0.79
    },
    {
      "word": "आ",
      "start": 26.148,
      "end": 26.349,
      "score": 0.908
    },
    {
      "word": "चुका",
      "start": 26.389,
      "end": 26.589,
      "score": 0.488
    },
    {
      "word": "था,",
      "start": 26.689,
      "end": 26.869,
      "score": 0.936
    },
    {
      "word": "और",
      "start": 27.23,
      "end": 27.31,
      "score": 0.806
    },
    {
      "word": "कर्ण",
      "start": 27.43,
      "end": 27.731,
      "score": 0.826
    },
    {
      "word": "अपने",
      "start": 27.851,
      "end": 28.131,
      "score": 0.811
    },
    {
      "word": "जन्मजात",
      "start": 28.272,
      "end": 28.872,
      "score": 0.672
    },
    {
      "word": "कवच",
      "start": 28.973,
      "end": 29.293,
      "score": 0.69
    },
    {
      "word": "के",
      "start": 29.353,
      "end": 29.433,
      "score": 0.71
    },
    {
      "word": "भरोसे",
      "start": 29.534,
      "end": 29.994,
      "score": 0.909
    },
    {
      "word": "निश्चिंत",
      "start": 30.094,
      "end": 30.555,
      "score": 0.644
    },
    {
      "word": "खड़ा",
      "start": 30.635,
      "end": 30.836,
      "score": 0.753
    },
    {
      "word": "था।",
      "start": 30.936,
      "end": 30.996,
      "score": 0.977
    }
  ],
  "B05": [
    {
      "word": "तभी",
      "start": 31.289,
      "end": 31.549,
      "score": 0.913
    },
    {
      "word": "एक",
      "start": 31.689,
      "end": 31.85,
      "score": 0.79
    },
    {
      "word": "दिन",
      "start": 31.93,
      "end": 32.05,
      "score": 0.829
    },
    {
      "word": "एक",
      "start": 32.15,
      "end": 32.27,
      "score": 0.99
    },
    {
      "word": "ब्राह्मण",
      "start": 32.39,
      "end": 32.771,
      "score": 0.456
    },
    {
      "word": "के",
      "start": 32.851,
      "end": 32.931,
      "score": 0.659
    },
    {
      "word": "वेश",
      "start": 33.051,
      "end": 33.291,
      "score": 0.598
    },
    {
      "word": "में",
      "start": 33.371,
      "end": 33.531,
      "score": 0.712
    },
    {
      "word": "एक",
      "start": 33.852,
      "end": 34.032,
      "score": 0.892
    },
    {
      "word": "याचक",
      "start": 34.132,
      "end": 34.432,
      "score": 0.918
    },
    {
      "word": "कर्ण",
      "start": 34.572,
      "end": 34.753,
      "score": 0.678
    },
    {
      "word": "के",
      "start": 34.853,
      "end": 34.913,
      "score": 0.707
    },
    {
      "word": "द्वार",
      "start": 34.993,
      "end": 35.213,
      "score": 0.598
    },
    {
      "word": "पर",
      "start": 35.313,
      "end": 35.473,
      "score": 0.758
    },
    {
      "word": "भिक्षा",
      "start": 35.814,
      "end": 36.094,
      "score": 0.47
    },
    {
      "word": "माँगने",
      "start": 36.174,
      "end": 36.474,
      "score": 0.916
    },
    {
      "word": "आ",
      "start": 36.574,
      "end": 36.715,
      "score": 0.998
    },
    {
      "word": "पहुँचा।",
      "start": 36.735,
      "end": 37.055,
      "score": 0.65
    }
  ],
  "B06": [
    {
      "word": "उस",
      "start": 37.389,
      "end": 37.55,
      "score": 0.986
    },
    {
      "word": "याचक",
      "start": 37.69,
      "end": 38.111,
      "score": 0.816
    },
    {
      "word": "ने",
      "start": 38.171,
      "end": 38.292,
      "score": 0.869
    },
    {
      "word": "कर्ण",
      "start": 38.452,
      "end": 38.713,
      "score": 0.587
    },
    {
      "word": "से",
      "start": 38.853,
      "end": 38.973,
      "score": 0.873
    },
    {
      "word": "और",
      "start": 39.134,
      "end": 39.334,
      "score": 0.74
    },
    {
      "word": "कुछ",
      "start": 39.455,
      "end": 39.655,
      "score": 0.978
    },
    {
      "word": "नहीं,",
      "start": 39.715,
      "end": 39.976,
      "score": 0.928
    },
    {
      "word": "बल्कि",
      "start": 40.217,
      "end": 40.518,
      "score": 0.614
    },
    {
      "word": "वही",
      "start": 40.638,
      "end": 40.879,
      "score": 0.893
    },
    {
      "word": "दिव्य",
      "start": 41.019,
      "end": 41.3,
      "score": 0.581
    },
    {
      "word": "कवच",
      "start": 41.42,
      "end": 41.741,
      "score": 0.769
    },
    {
      "word": "और",
      "start": 41.861,
      "end": 41.981,
      "score": 0.918
    },
    {
      "word": "कुंडल",
      "start": 42.122,
      "end": 42.423,
      "score": 0.875
    },
    {
      "word": "माँग",
      "start": 42.503,
      "end": 42.723,
      "score": 0.552
    },
    {
      "word": "लिए,",
      "start": 42.764,
      "end": 43.064,
      "score": 0.683
    },
    {
      "word": "जो",
      "start": 43.385,
      "end": 43.506,
      "score": 0.597
    },
    {
      "word": "उसकी",
      "start": 43.606,
      "end": 43.887,
      "score": 0.912
    },
    {
      "word": "रक्षा",
      "start": 43.947,
      "end": 44.268,
      "score": 0.599
    },
    {
      "word": "करते",
      "start": 44.368,
      "end": 44.669,
      "score": 0.818
    },
    {
      "word": "थे।",
      "start": 44.769,
      "end": 44.829,
      "score": 0.966
    }
  ],
  "B07": [
    {
      "word": "कर्ण",
      "start": 45.17,
      "end": 45.491,
      "score": 0.803
    },
    {
      "word": "भली-भाँति",
      "start": 45.611,
      "end": 46.212,
      "score": 0.667
    },
    {
      "word": "जानता",
      "start": 46.332,
      "end": 46.673,
      "score": 0.864
    },
    {
      "word": "था",
      "start": 46.773,
      "end": 46.953,
      "score": 0.974
    },
    {
      "word": "कि",
      "start": 47.214,
      "end": 47.274,
      "score": 0.958
    },
    {
      "word": "यह",
      "start": 47.354,
      "end": 47.434,
      "score": 0.702
    },
    {
      "word": "याचक",
      "start": 47.574,
      "end": 47.975,
      "score": 0.84
    },
    {
      "word": "असल",
      "start": 48.055,
      "end": 48.336,
      "score": 0.889
    },
    {
      "word": "में",
      "start": 48.396,
      "end": 48.496,
      "score": 0.828
    },
    {
      "word": "कौन",
      "start": 48.596,
      "end": 48.817,
      "score": 0.646
    },
    {
      "word": "है,",
      "start": 48.877,
      "end": 49.037,
      "score": 0.951
    },
    {
      "word": "फिर",
      "start": 49.358,
      "end": 49.518,
      "score": 0.743
    },
    {
      "word": "भी",
      "start": 49.598,
      "end": 49.718,
      "score": 0.996
    },
    {
      "word": "उसने",
      "start": 49.838,
      "end": 50.159,
      "score": 0.958
    },
    {
      "word": "उसे",
      "start": 50.199,
      "end": 50.399,
      "score": 0.845
    },
    {
      "word": "मना",
      "start": 50.5,
      "end": 50.76,
      "score": 0.916
    },
    {
      "word": "करना",
      "start": 50.86,
      "end": 51.181,
      "score": 0.903
    },
    {
      "word": "उचित",
      "start": 51.321,
      "end": 51.542,
      "score": 0.498
    },
    {
      "word": "नहीं",
      "start": 51.642,
      "end": 51.842,
      "score": 0.834
    },
    {
      "word": "समझा।",
      "start": 51.942,
      "end": 52.223,
      "score": 0.723
    }
  ],
  "B08": [
    {
      "word": "बिना",
      "start": 52.576,
      "end": 52.777,
      "score": 0.896
    },
    {
      "word": "कोई",
      "start": 52.857,
      "end": 52.977,
      "score": 0.652
    },
    {
      "word": "झिझक",
      "start": 53.078,
      "end": 53.379,
      "score": 0.628
    },
    {
      "word": "दिखाए,",
      "start": 53.439,
      "end": 53.84,
      "score": 0.872
    },
    {
      "word": "कर्ण",
      "start": 54.181,
      "end": 54.361,
      "score": 0.44
    },
    {
      "word": "ने",
      "start": 54.401,
      "end": 54.502,
      "score": 0.889
    },
    {
      "word": "अपना",
      "start": 54.522,
      "end": 54.783,
      "score": 0.72
    },
    {
      "word": "कवच",
      "start": 54.883,
      "end": 55.124,
      "score": 0.558
    },
    {
      "word": "और",
      "start": 55.244,
      "end": 55.324,
      "score": 0.762
    },
    {
      "word": "कुंडल",
      "start": 55.444,
      "end": 55.765,
      "score": 0.698
    },
    {
      "word": "स्वयं",
      "start": 55.866,
      "end": 56.106,
      "score": 0.531
    },
    {
      "word": "उतारकर",
      "start": 56.146,
      "end": 56.728,
      "score": 0.762
    },
    {
      "word": "उस",
      "start": 57.049,
      "end": 57.23,
      "score": 0.981
    },
    {
      "word": "याचक",
      "start": 57.29,
      "end": 57.591,
      "score": 0.578
    },
    {
      "word": "को",
      "start": 57.671,
      "end": 57.751,
      "score": 0.981
    },
    {
      "word": "सौंप",
      "start": 57.871,
      "end": 58.072,
      "score": 0.612
    },
    {
      "word": "दिए।",
      "start": 58.152,
      "end": 58.313,
      "score": 0.658
    }
  ],
  "B09": [
    {
      "word": "क्योंकि",
      "start": 58.587,
      "end": 58.927,
      "score": 0.745
    },
    {
      "word": "कर्ण",
      "start": 59.128,
      "end": 59.368,
      "score": 0.619
    },
    {
      "word": "के",
      "start": 59.468,
      "end": 59.568,
      "score": 0.832
    },
    {
      "word": "लिए",
      "start": 59.648,
      "end": 59.868,
      "score": 0.904
    },
    {
      "word": "दान",
      "start": 60.028,
      "end": 60.289,
      "score": 0.875
    },
    {
      "word": "का",
      "start": 60.409,
      "end": 60.489,
      "score": 0.977
    },
    {
      "word": "अर्थ",
      "start": 60.669,
      "end": 60.929,
      "score": 0.84
    },
    {
      "word": "केवल",
      "start": 61.049,
      "end": 61.35,
      "score": 0.836
    },
    {
      "word": "कोई",
      "start": 61.49,
      "end": 61.69,
      "score": 0.812
    },
    {
      "word": "वस्तु",
      "start": 61.77,
      "end": 62.11,
      "score": 0.649
    },
    {
      "word": "देना",
      "start": 62.19,
      "end": 62.451,
      "score": 0.736
    },
    {
      "word": "नहीं",
      "start": 62.531,
      "end": 62.771,
      "score": 0.754
    },
    {
      "word": "था,",
      "start": 62.871,
      "end": 63.051,
      "score": 0.754
    },
    {
      "word": "बल्कि",
      "start": 63.291,
      "end": 63.572,
      "score": 0.811
    },
    {
      "word": "अपने",
      "start": 63.632,
      "end": 63.912,
      "score": 0.77
    },
    {
      "word": "दिए",
      "start": 64.032,
      "end": 64.252,
      "score": 0.671
    },
    {
      "word": "हुए",
      "start": 64.372,
      "end": 64.553,
      "score": 0.884
    },
    {
      "word": "वचन",
      "start": 64.673,
      "end": 64.993,
      "score": 0.778
    },
    {
      "word": "को",
      "start": 65.113,
      "end": 65.253,
      "score": 0.892
    },
    {
      "word": "हर",
      "start": 65.494,
      "end": 65.674,
      "score": 0.962
    },
    {
      "word": "हाल",
      "start": 65.854,
      "end": 66.094,
      "score": 0.903
    },
    {
      "word": "में",
      "start": 66.174,
      "end": 66.254,
      "score": 0.853
    },
    {
      "word": "निभाना",
      "start": 66.314,
      "end": 66.755,
      "score": 0.727
    },
    {
      "word": "था।",
      "start": 66.895,
      "end": 66.935,
      "score": 0.937
    }
  ],
  "B10": [
    {
      "word": "अपनी",
      "start": 67.268,
      "end": 67.569,
      "score": 0.916
    },
    {
      "word": "सबसे",
      "start": 67.67,
      "end": 68.031,
      "score": 0.994
    },
    {
      "word": "बड़ी",
      "start": 68.151,
      "end": 68.352,
      "score": 0.418
    },
    {
      "word": "सुरक्षा",
      "start": 68.452,
      "end": 68.894,
      "score": 0.736
    },
    {
      "word": "खोकर",
      "start": 69.035,
      "end": 69.356,
      "score": 0.798
    },
    {
      "word": "भी,",
      "start": 69.456,
      "end": 69.617,
      "score": 0.954
    },
    {
      "word": "कर्ण",
      "start": 69.958,
      "end": 70.259,
      "score": 0.829
    },
    {
      "word": "ने",
      "start": 70.299,
      "end": 70.4,
      "score": 0.833
    },
    {
      "word": "अपना",
      "start": 70.44,
      "end": 70.701,
      "score": 0.857
    },
    {
      "word": "धर्म",
      "start": 70.821,
      "end": 71.142,
      "score": 0.674
    },
    {
      "word": "और",
      "start": 71.263,
      "end": 71.383,
      "score": 0.99
    },
    {
      "word": "अपना",
      "start": 71.423,
      "end": 71.684,
      "score": 0.874
    },
    {
      "word": "वचन",
      "start": 71.805,
      "end": 72.126,
      "score": 0.608
    },
    {
      "word": "कभी",
      "start": 72.206,
      "end": 72.427,
      "score": 0.849
    },
    {
      "word": "नहीं",
      "start": 72.467,
      "end": 72.688,
      "score": 0.827
    },
    {
      "word": "खोया।",
      "start": 72.768,
      "end": 72.989,
      "score": 0.867
    }
  ]
} as const;
