// Generated by src/produce.ts — do not edit manually.
export const runtimeManifest = {
  "project_id": "karna-full-journey",
  "title": "कर्ण — सूर्यपुत्र की पूरी गाथा",
  "language": "hi-IN",
  "duration_seconds": 169.49,
  "characters": [
    "karna",
    "indra",
    "kunti",
    "duryodhana"
  ],
  "asset_kinds": {
    "karna": "character",
    "indra": "character",
    "kunti": "character",
    "duryodhana": "character",
    "surya_glow": "environment",
    "kurukshetra_battlefield": "environment",
    "ashwa_river": "environment",
    "kavach_kundal": "prop",
    "tournament_arena": "environment"
  },
  "asset_sacred": {
    "karna": true,
    "indra": true,
    "kunti": true,
    "duryodhana": false,
    "tournament_arena": false
  },
  "asset_visual_direction": {
    "karna": "Dignified Suryaputra warrior — golden kavach fused to his chest, kundala earrings, regal but weathered bearing. Hand-illustrated Indian mythology style: cream parchment, black ink linework, restrained gold/red accents. Never comedic, never generic.",
    "indra": "Regal deity concealed as an aged Brahmin mendicant — modest robes but unmistakable dignity and quiet radiance beneath the disguise. Reverent, never a comic beggar caricature.",
    "kunti": "Young royal princess in fine but modest attire, expressive anguish and dignity — dignified sorrow, never melodramatic. Hand-illustrated ink style matching the rest of the cast.",
    "duryodhana": "Proud Kuru prince in regal warrior attire, confident bearing, a genuine warmth toward Karna in his expression despite his more commonly antagonistic role elsewhere in the epic — this is his loyal-friend moment.",
    "surya_glow": "A stylized sun-ring/glow motif representing Surya's divine gift and Karna's radiance — ornamental, not literal scenery.",
    "kurukshetra_battlefield": "Vast dust-lit battlefield under a tense sky, distant war tents and banners, restrained ink-wash atmosphere — foreboding, not gory.",
    "ashwa_river": "A quiet river at dawn, soft mist, a small basket motif implied through composition — tender and sorrowful, not desolate. Same hand-illustrated ink/gold/red palette as the rest of the cast.",
    "tournament_arena": "A royal open-air tournament ground for a public archery demonstration: a raised wooden dais and royal pavilion with banners at one side, a semicircle of watching nobles and commoners suggested in silhouette/ink-wash at the edges, an open sandy arena floor in the foreground with a single practice target, dust haze in the afternoon light. Same hand-illustrated ink/gold/red palette as the rest of the cast, composed with a clear open foreground so a character can be staged inside it later."
  },
  "beats": [
    {
      "beat_id": "H1",
      "duration_seconds": 7.93,
      "visual_role": "hook",
      "asset_refs": [
        "karna",
        "surya_glow"
      ],
      "camera": "push_in",
      "text": "पहचान",
      "narration": "यह कहानी एक ऐसे योद्धा की है, जो जन्म से राजकुमार था, पर जाना गया एक सारथी के पुत्र के नाम से।",
      "pace": "measured",
      "shot_type": "wide",
      "composition": "Karna centered, spear raised, sun motif behind",
      "visual_action": "Karna's entrance settles into frame as the ink reveal draws him in",
      "reveal": true,
      "keyword_text": "पहचान",
      "transition": "cut"
    },
    {
      "beat_id": "H2",
      "duration_seconds": 8.22,
      "visual_role": "armor_reveal",
      "asset_refs": [
        "karna",
        "kavach_kundal",
        "ashwa_river"
      ],
      "camera": "slow_push",
      "text": "सुरक्षा",
      "narration": "और जिस दिन उसकी असली पहचान सामने आई, वह पहले ही अपनी सबसे बड़ी सुरक्षा किसी और को दे चुका था।",
      "pace": "slow",
      "shot_type": "face",
      "composition": "Tight on Karna's face, contemplative",
      "visual_action": "Slow settle on Karna's expression, foreshadowing the sacrifice to come",
      "reveal": false,
      "keyword_text": "सुरक्षा",
      "transition": "ink-wipe"
    },
    {
      "beat_id": "S1",
      "duration_seconds": 9.51,
      "visual_role": "setup",
      "asset_refs": [
        "kunti",
        "surya_glow"
      ],
      "camera": "tilt_up",
      "text": "वरदान",
      "narration": "यह कथा शुरू होती है राजकुमारी कुंती से, जिन्हें एक दिव्य मंत्र का वरदान मिला था — जिससे वे किसी भी देवता का आवाहन कर सकती थीं।",
      "sfx": [
        "soft chime"
      ],
      "pace": "measured",
      "shot_type": "face, prayer",
      "composition": "Kunti in prayer, hands raised, ethereal light",
      "visual_action": "Kunti invokes the mantra; a faint divine glow builds",
      "reveal": true,
      "keyword_text": "वरदान",
      "transition": "cut"
    },
    {
      "beat_id": "S2",
      "duration_seconds": 12.66,
      "visual_role": "setup",
      "asset_refs": [
        "kunti",
        "surya_glow"
      ],
      "camera": "pull_back",
      "text": "जन्म",
      "narration": "बाल्यावस्था की जिज्ञासा में, कुंती ने सूर्यदेव का आवाहन किया। उसी क्षण, सूर्यदेव के आशीर्वाद से एक पुत्र का जन्म हुआ — कवच और कुंडल सहित, उसके शरीर से जुड़े हुए।",
      "sfx": [
        "soft chime"
      ],
      "pace": "measured",
      "shot_type": "two-shot, radiant",
      "composition": "Kunti and the sun motif, birth implied through light",
      "visual_action": "Sun-ring pulses brightly at the moment of birth",
      "reveal": false,
      "keyword_text": "जन्म",
      "transition": "cut"
    },
    {
      "beat_id": "S3",
      "duration_seconds": 8.7,
      "visual_role": "abandonment",
      "asset_refs": [
        "kunti",
        "ashwa_river"
      ],
      "camera": "pan",
      "text": "त्याग",
      "narration": "समाज के भय से, अविवाहित कुंती को अपने नवजात पुत्र को एक टोकरी में नदी में बहा देना पड़ा। वह पुत्र था — कर्ण।",
      "sfx": [
        "water flowing"
      ],
      "pace": "slow",
      "shot_type": "wide, river",
      "composition": "Kunti alone at the river bank, sorrowful",
      "visual_action": "Kunti sets the basket adrift; camera lingers on the water",
      "reveal": false,
      "keyword_text": "त्याग",
      "transition": "ink-wipe"
    },
    {
      "beat_id": "E1",
      "duration_seconds": 10.18,
      "visual_role": "rescue",
      "asset_refs": [
        "karna",
        "ashwa_river"
      ],
      "camera": "reveal_from_edge",
      "text": "अधिरथ",
      "narration": "अश्व नदी में बहता हुआ वह टोकरी सारथी अधिरथ और उनकी पत्नी राधा को मिली। उन्होंने बिना किसी भेदभाव के, उसे अपने पुत्र की तरह पाला।",
      "pace": "measured",
      "shot_type": "wide, river",
      "composition": "The basket arriving at the bank, a new life beginning",
      "visual_action": "Camera pulls back from the river as the rescue is implied",
      "reveal": true,
      "keyword_text": "अधिरथ",
      "transition": "cut"
    },
    {
      "beat_id": "E2",
      "duration_seconds": 10.43,
      "visual_role": "rejection",
      "asset_refs": [
        "karna",
        "tournament_arena"
      ],
      "camera": "armor_crop",
      "text": "द्रोणाचार्य",
      "narration": "कर्ण बड़ा होकर एक असाधारण धनुर्धर बना। पर गुरु द्रोणाचार्य ने उसे केवल इसलिए शिक्षा देने से मना कर दिया, क्योंकि वह एक सूत-पुत्र था।",
      "pace": "measured",
      "shot_type": "face, hand/bow detail",
      "composition": "Karna practicing archery, focused",
      "visual_action": "Karna's hands draw a bow; subtle parallax on the weapon",
      "reveal": false,
      "keyword_text": "द्रोणाचार्य",
      "transition": "cut"
    },
    {
      "beat_id": "E3",
      "duration_seconds": 9.28,
      "visual_role": "rejection",
      "asset_refs": [
        "karna",
        "tournament_arena"
      ],
      "camera": "shot_reverse",
      "text": "सूत-पुत्र",
      "narration": "एक खुले प्रदर्शन में, कृपाचार्य ने सबके सामने उसके कुल पर प्रश्न उठाया — कि एक सारथी-पुत्र राजकुमारों को चुनौती कैसे दे सकता है।",
      "pace": "quick",
      "shot_type": "face reaction",
      "composition": "Karna's face reacting to public humiliation",
      "visual_action": "Quick cut to Karna's controlled but wounded expression",
      "reveal": false,
      "keyword_text": "सूत-पुत्र",
      "transition": "cut"
    },
    {
      "beat_id": "E4",
      "duration_seconds": 10.8,
      "visual_role": "elevation",
      "asset_refs": [
        "karna",
        "duryodhana",
        "tournament_arena"
      ],
      "camera": "reverse_push",
      "text": "अंग देश",
      "narration": "उसी क्षण दुर्योधन आगे आया, और कर्ण को तुरंत अंग देश का राजा घोषित कर दिया — एक मित्रता की शुरुआत, जो कर्ण के जीवन भर निभाई गई।",
      "sfx": [
        "crowd murmur"
      ],
      "pace": "measured",
      "shot_type": "two-shot",
      "composition": "Duryodhana stepping toward Karna, both in frame",
      "visual_action": "Duryodhana's decisive gesture of declaring Karna's kingship",
      "reveal": true,
      "keyword_text": "अंग देश",
      "transition": "cut"
    },
    {
      "beat_id": "T1",
      "duration_seconds": 8.32,
      "visual_role": "decision",
      "asset_refs": [
        "karna",
        "kurukshetra_battlefield"
      ],
      "camera": "shot_reverse",
      "text": "प्रस्ताव",
      "narration": "युद्ध से पहले, कृष्ण और स्वयं कुंती ने कर्ण को उसका सच्चा जन्म बताया, और पांडवों की ओर से राज्य का प्रस्ताव दिया।",
      "pace": "measured",
      "shot_type": "two-shot, wide",
      "composition": "Karna facing an unseen Krishna/Kunti presence, offer implied",
      "visual_action": "Subtle parallax as the weight of the offer settles over Karna",
      "reveal": false,
      "keyword_text": "प्रस्ताव",
      "transition": "cut"
    },
    {
      "beat_id": "T2",
      "duration_seconds": 10.96,
      "visual_role": "loyalty",
      "asset_refs": [
        "karna",
        "kurukshetra_battlefield"
      ],
      "camera": "slow_push",
      "text": "वफ़ादारी",
      "narration": "पर कर्ण ने अपना जन्मसिद्ध अधिकार नहीं, बल्कि दुर्योधन के प्रति अपनी वफ़ादारी चुनी — क्योंकि धर्म उसके लिए सिर्फ खून का रिश्ता नहीं था।",
      "pace": "slow",
      "shot_type": "face, resolute",
      "composition": "Close on Karna's resolved expression",
      "visual_action": "Karna's expression hardens into resolve",
      "reveal": false,
      "keyword_text": "वफ़ादारी",
      "transition": "ink-wipe"
    },
    {
      "beat_id": "R1",
      "duration_seconds": 9.32,
      "visual_role": "visitor_reveal",
      "asset_refs": [
        "indra",
        "ashwa_river"
      ],
      "camera": "reveal_from_edge",
      "text": "याचक",
      "narration": "कुरुक्षेत्र युद्ध निकट था, जब एक ब्राह्मण के वेश में एक याचक कर्ण के द्वार पर आया — वह वास्तव में इंद्र थे, अर्जुन के पिता।",
      "sfx": [
        "footsteps"
      ],
      "pace": "measured",
      "shot_type": "entrance, edge reveal",
      "composition": "Indra's disguised figure emerging from frame edge",
      "visual_action": "Indra's figure draws in from the side as he arrives",
      "reveal": true,
      "keyword_text": "याचक",
      "transition": "cut"
    },
    {
      "beat_id": "R2",
      "duration_seconds": 8.76,
      "visual_role": "decision",
      "asset_refs": [
        "karna",
        "indra",
        "ashwa_river"
      ],
      "camera": "shot_reverse",
      "text": "पहचान",
      "narration": "कर्ण, जो प्रतिदिन सूर्य की पूजा करते हुए किसी भी याचक को खाली हाथ नहीं भेजता था, तुरंत पहचान गया कि यह याचक कौन था।",
      "pace": "slow",
      "shot_type": "face, eyes",
      "composition": "Close on Karna's eyes registering recognition",
      "visual_action": "Karna's expression settles into quiet recognition",
      "reveal": false,
      "keyword_text": "पहचान",
      "transition": "cut"
    },
    {
      "beat_id": "C1",
      "duration_seconds": 8.32,
      "visual_role": "sacrifice",
      "asset_refs": [
        "karna",
        "kavach_kundal",
        "ashwa_river"
      ],
      "camera": "armor_crop",
      "text": "त्याग",
      "narration": "बिना एक पल गंवाए, कर्ण ने अपना जन्मजात कवच और कुंडल स्वयं उतारा — अपनी सबसे बड़ी सुरक्षा को अपने ही हाथों से त्याग दिया।",
      "sfx": [
        "soft cloth/metal unclasp"
      ],
      "pace": "slow",
      "shot_type": "hand/armor detail",
      "composition": "Hands unclasping the armor, gold fading from the body",
      "visual_action": "Karna's hands remove the armor; gold light fades as it leaves him",
      "reveal": false,
      "keyword_text": "त्याग",
      "transition": "cut"
    },
    {
      "beat_id": "C2",
      "duration_seconds": 7.7,
      "visual_role": "sacrifice",
      "asset_refs": [
        "karna",
        "indra",
        "kavach_kundal",
        "ashwa_river"
      ],
      "camera": "pull_back",
      "text": "दान",
      "narration": "उसने वह दिव्य कवच याचक को सौंप दिया, यह जानते हुए भी कि अब वह युद्ध में पहले जैसा अजेय नहीं रहेगा।",
      "pace": "slow",
      "shot_type": "two-shot",
      "composition": "The armor changing hands between the two figures",
      "visual_action": "The kavach passes from Karna's hands to Indra's",
      "reveal": false,
      "keyword_text": "दान",
      "transition": "cut"
    },
    {
      "beat_id": "P1",
      "duration_seconds": 7.96,
      "visual_role": "payoff",
      "asset_refs": [
        "karna",
        "indra",
        "ashwa_river"
      ],
      "camera": "reverse_push",
      "text": "शक्ति",
      "narration": "प्रभावित होकर इंद्र ने बदले में कर्ण को एक बार प्रयोग होने वाला शक्ति अस्त्र दिया — एक निश्चित विजय का हथियार।",
      "sfx": [
        "soft gold shimmer"
      ],
      "pace": "measured",
      "shot_type": "two-shot",
      "composition": "Indra offering the Shakti weapon in return",
      "visual_action": "A glowing weapon motif passes to Karna",
      "reveal": false,
      "keyword_text": "शक्ति",
      "transition": "cut"
    },
    {
      "beat_id": "P2",
      "duration_seconds": 9.77,
      "visual_role": "payoff",
      "asset_refs": [
        "karna",
        "surya_glow"
      ],
      "camera": "slow_push",
      "text": "धर्म",
      "narration": "पर कर्ण जानता था, उसने अपनी सबसे बड़ी सुरक्षा दान में दे दी थी — केवल इसलिए, क्योंकि दान माँगने वाले को कभी मना नहीं करना उसका धर्म था।",
      "pace": "measured",
      "shot_type": "face, settling",
      "composition": "Karna alone, calm reflection",
      "visual_action": "Slow settle on Karna's peaceful acceptance",
      "reveal": false,
      "keyword_text": "धर्म",
      "transition": "cut"
    },
    {
      "beat_id": "P3",
      "duration_seconds": 10.67,
      "visual_role": "payoff",
      "asset_refs": [
        "karna",
        "surya_glow"
      ],
      "camera": "slow_push",
      "text": "सत्य",
      "narration": "यही थी कर्ण की सच्ची पहचान — एक ऐसा दानवीर, जिसने अपने वचन और अपने धर्म को, अपने ही जीवन से भी ऊपर रखा।",
      "pace": "slow",
      "shot_type": "wide, final",
      "composition": "Karna standing tall, sun motif fully behind him",
      "visual_action": "Final slow push as the ink settles into the closing image",
      "reveal": false,
      "keyword_text": "सत्य",
      "transition": "cut"
    }
  ],
  "audio": {
    "voice_style": "Warm, reverent Hindi male storyteller voice — measured and dignified, sustained across a longer narrative arc, not theatrical or rushed.",
    "target_wpm": 155,
    "music_direction": "Sparse tanpura/string drone underneath throughout, swelling gently at Duryodhana's coronation, the decision, and the sacrifice — never overpowering the narration; near-silent during the setup/river sequence.",
    "silence_guidance": "No pause longer than 0.5s except a held beat before T2's decision and before C1's sacrifice.",
    "music_path": "projects/karna-full-journey/audio/music.wav",
    "sfx_dir": "projects/karna-full-journey/audio/sfx"
  }
} as const;
