import {useEffect, useState} from 'react';
import {api} from '../../api';

const TRACKS = [
  {label: 'Narration (Chatterbox TTS)', path: 'audio/narration.wav'},
  {label: 'Final mix', path: 'audio/final-mix.wav'},
];

export default function AudioTab({projectId}: {projectId: string}) {
  const [existing, setExisting] = useState<Record<string, boolean>>({});
  const [report, setReport] = useState<Record<string, unknown> | null>(null);

  useEffect(() => {
    Promise.all(TRACKS.map(async (t) => {
      const res = await fetch(api.fileUrl(projectId, t.path), {method: 'HEAD'});
      return [t.path, res.ok] as const;
    })).then((entries) => setExisting(Object.fromEntries(entries)));
    api.getQa(projectId).then((qa) => setReport((qa.audio_report?.content as Record<string, unknown>) ?? null));
  }, [projectId]);

  return (
    <div className="stack">
      <div className="card">
        <h3>Audio tracks</h3>
        <p className="hint">Generated by the existing Chatterbox TTS + Whisper alignment + mix pipeline (Production tab) — not re-implemented here.</p>
        {TRACKS.map((t) => (
          <div key={t.path} style={{marginBottom: 16}}>
            <div className="row-between" style={{marginBottom: 4}}>
              <strong>{t.label}</strong>
              <span className={`badge ${existing[t.path] ? 'badge-rendered' : 'badge-draft'}`}>{existing[t.path] ? 'available' : 'not generated'}</span>
            </div>
            {existing[t.path] ? <audio controls style={{width: '100%'}} src={api.fileUrl(projectId, t.path)} /> : null}
          </div>
        ))}
      </div>
      {report ? (
        <div className="card">
          <h3>Audio duration report</h3>
          <table className="kv-table">
            <tbody>
              {Object.entries(report).map(([k, v]) => <tr key={k}><td>{k}</td><td>{String(v)}</td></tr>)}
            </tbody>
          </table>
        </div>
      ) : null}
    </div>
  );
}
