import {createServer} from 'node:http';
import {existsSync} from 'node:fs';
import {mkdir, readdir, readFile, rm, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const PROJECTS = path.join(ROOT, 'projects');
const PORT = Number(process.env.STUDIO_PORT || 4317);
const FILES = ['project.json','story.json','script.json','manifest.json','characters.json','metadata.json'];
const safeId = (v) => String(v || '').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80);
const pdir = (id) => path.join(PROJECTS,safeId(id));
const send = (res,status,data) => {res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};
async function body(req){let s='';for await(const c of req)s+=c;return s?JSON.parse(s):{};}
async function summary(id){const dir=pdir(id);const p=JSON.parse(await readFile(path.join(dir,'project.json'),'utf8'));const renders=existsSync(path.join(dir,'renders'))?await readdir(path.join(dir,'renders')):[];return {...p,id:safeId(id),files:FILES.filter(f=>existsSync(path.join(dir,f))),renders};}
async function create(input){const id=safeId(input.project_id||input.project_name||input.name);if(!id)throw Error('Project name is required');const dir=pdir(id);if(existsSync(dir))throw Error(`Project already exists: ${id}`);for(const d of ['assets','audio','renders','qa'])await mkdir(path.join(dir,d),{recursive:true});const p={project_id:id,project_name:input.project_name||input.name,title:input.title||input.project_name||input.name,format:input.format==='longform'?'longform':'short',language:input.language||'hi-IN',target_duration_seconds:Number(input.target_duration_seconds||(input.format==='longform'?600:75)),brand:{name:'KATHAAYA',tagline:'ANCIENT STORIES. REIMAGINED THROUGH INK.'}};await writeFile(path.join(dir,'project.json'),JSON.stringify(p,null,2)+'\n');for(const f of FILES.slice(1))await writeFile(path.join(dir,f),'{}\n');return summary(id);}
async function importPkg(pkg){if(!pkg||typeof pkg!=='object')throw Error('Package must be a JSON object');for(const k of ['project','story','script','characters','environments','props','visual_manifest','audio','metadata','sources'])if(!(k in pkg))throw Error(`Missing package field: ${k}`);const p=await create({...pkg.project,project_name:pkg.project.project_name||pkg.project.title||'Untitled'});const dir=pdir(p.id);const data={'project.json':{...p,...pkg.project,project_id:p.id,brand:p.brand},'story.json':pkg.story,'script.json':pkg.script,'manifest.json':pkg.manifest||pkg.visual_manifest,'characters.json':{characters:pkg.characters||[]},'metadata.json':pkg.metadata};for(const [f,v] of Object.entries(data))await writeFile(path.join(dir,f),JSON.stringify(v??{},null,2)+'\n');return summary(p.id);}
const server=createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/'){const html=await readFile(path.join(ROOT,'studio','index.html'));res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(html);}if(req.method==='GET'&&u.pathname==='/api/projects'){await mkdir(PROJECTS,{recursive:true});const ds=await readdir(PROJECTS,{withFileTypes:true});const out=[];for(const d of ds.filter(x=>x.isDirectory()))try{out.push(await summary(d.name));}catch{}return send(res,200,out);}if(req.method==='POST'&&u.pathname==='/api/projects')return send(res,201,await create(await body(req)));if(req.method==='POST'&&u.pathname==='/api/projects/import')return send(res,201,await importPkg(await body(req)));const m=u.pathname.match(/^\/api\/projects\/([^/]+)(?:\/([^/]+))?$/);if(m){const id=safeId(m[1]),action=m[2],dir=pdir(id);if(req.method==='GET'&&!action){if(!existsSync(dir))return send(res,404,{error:'Not found'});const fs={};for(const f of FILES)if(existsSync(path.join(dir,f)))fs[f]=JSON.parse(await readFile(path.join(dir,f),'utf8'));return send(res,200,{project:await summary(id),files:fs});}if(req.method==='DELETE'&&!action){await rm(dir,{recursive:true,force:true});return send(res,200,{ok:true});}if(req.method==='PUT'&&FILES.includes(action)){const b=await body(req);JSON.parse(b.content);await writeFile(path.join(dir,action),b.content.endsWith('\n')?b.content:b.content+'\n');return send(res,200,{ok:true});}}return send(res,404,{error:'Not found'});}catch(e){return send(res,400,{error:e instanceof Error?e.message:String(e)});}});
await mkdir(PROJECTS,{recursive:true});server.listen(PORT,'127.0.0.1',()=>console.log(`Kathaaya Studio: http://127.0.0.1:${PORT}`));
