import {existsSync} from 'node:fs';
import {mkdir, readFile, writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {runCommand} from './adapters/command';
import type {ProductionManifest} from './pipeline/types';

const input = process.argv[2] ?? 'examples/karna-short.json';
const manifest = JSON.parse(await readFile(input, 'utf8')) as ProductionManifest;
const audioPath = manifest.audio?.narration_path ?? join('projects', manifest.project_id, 'audio', 'narration.wav');
const segmentsPath = `${audioPath}.segments.json`;
const strict = process.env.REQUIRE_WHISPER_ALIGNMENT === '1';

const logDir = join('projects', manifest.project_id, 'logs');
await mkdir(logDir, {recursive: true});
const reportPath = join(logDir, 'whisper-alignment.json');

const fail = (message: string) => {
  if (strict) throw new Error(message);
  console.warn(`[whisper-align] ${message}`);
};

const writeEmptyRuntimeCaptions = async () => {
  await writeFile(
    'src/remotion/runtime-captions.ts',
    "// Generated by src/align-whisper.ts — do not edit manually.\nexport const runtimeCaptions: Record<string, Array<{word: string; start: number; end: number; score: number}>> = {} as const;\n",
    'utf8',
  );
};

if (!existsSync(audioPath)) {
  fail(`Narration file not found: ${audioPath}`);
  await writeEmptyRuntimeCaptions();
  process.exit(strict ? 1 : 0);
}
if (!existsSync(segmentsPath)) {
  fail(`Narration segment-timing sidecar not found: ${segmentsPath} (expected from tools/chatterbox_tts.py)`);
  await writeEmptyRuntimeCaptions();
  process.exit(strict ? 1 : 0);
}

const command = (process.env.WHISPER_ALIGN_COMMAND ?? 'python3').trim();
const argsTemplate = (process.env.WHISPER_ALIGN_ARGS ?? 'tools/whisper_align.py {audio} {segments} {output}').trim();
const args = argsTemplate.split(/\s+/).filter(Boolean).map((token) => token
  .replaceAll('{audio}', audioPath)
  .replaceAll('{segments}', segmentsPath)
  .replaceAll('{output}', reportPath));

console.log(`[whisper-align] aligning ${audioPath} against known script text`);
const result = await runCommand(command, args);
if (result.code !== 0 || !existsSync(reportPath)) {
  fail(`Whisper alignment failed or did not produce ${reportPath}: ${result.stderr.trim() || result.stdout.trim()}`);
  await writeEmptyRuntimeCaptions();
  process.exit(strict ? 1 : 0);
}

const report = JSON.parse(await readFile(reportPath, 'utf8')) as {beats: Array<{beat_id: string; words: Array<{word: string; start: number; end: number; score: number}>}>};
const captions: Record<string, Array<{word: string; start: number; end: number; score: number}>> = {};
let totalWords = 0;
for (const beat of report.beats) {
  captions[beat.beat_id] = beat.words;
  totalWords += beat.words.length;
}

const runtimeSource = `// Generated by src/align-whisper.ts — do not edit manually.\nexport const runtimeCaptions: Record<string, Array<{word: string; start: number; end: number; score: number}>> = ${JSON.stringify(captions, null, 2)} as const;\n`;
await writeFile('src/remotion/runtime-captions.ts', runtimeSource, 'utf8');

console.log(`[whisper-align] ${report.beats.length} beats, ${totalWords} words aligned`);
console.log(`[whisper-align] report: ${reportPath}`);
