import {existsSync} from 'node:fs';
import {mkdir, readFile, writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import type {ProductionManifest} from './pipeline/types';

export type WordTiming = {text: string; start_seconds: number; end_seconds: number; index: number};
export type TimingMap = Record<string, WordTiming[]>;

const input = process.argv[2] ?? 'examples/karna-short.json';
const manifest = JSON.parse(await readFile(input, 'utf8')) as ProductionManifest;
const root = join('projects', manifest.project_id);
const logsDir = join(root, 'logs');
const timingDir = join(root, 'timing');
await mkdir(logsDir, {recursive: true});
await mkdir(timingDir, {recursive: true});

const alignmentPath = join(logsDir, 'audio-alignment-report.json');
const runtimePath = 'src/remotion/runtime-timing.ts';
const report = existsSync(alignmentPath)
  ? JSON.parse(await readFile(alignmentPath, 'utf8')) as {beats?: Array<{beat_id: string; start_seconds: number; end_seconds: number; speech_seconds: number; leading_silence_seconds: number}>}
  : undefined;

const timingByBeat = new Map((report?.beats ?? []).map((beat) => [beat.beat_id, beat]));
const map: TimingMap = {};
let cursor = 0;

for (const beat of manifest.beats) {
  const text = (beat.narration ?? beat.text ?? '').trim();
  const beatStart = cursor;
  const beatEnd = cursor + beat.duration_seconds;
  cursor = beatEnd;
  if (!text) continue;

  const words = text.split(/\s+/).filter(Boolean);
  const aligned = timingByBeat.get(beat.beat_id);
  const speechStart = aligned
    ? Math.min(beatEnd, Math.max(beatStart, beatStart + aligned.leading_silence_seconds))
    : beatStart + Math.min(0.12, beat.duration_seconds * 0.04);
  const speechDuration = aligned
    ? Math.max(0.2, Math.min(beatEnd - speechStart, aligned.speech_seconds))
    : Math.max(0.25, beatEnd - speechStart);

  const weights = words.map((word) => Math.max(1, [...word].length));
  const totalWeight = weights.reduce((sum, value) => sum + value, 0);
  let wordCursor = speechStart;
  map[beat.beat_id] = words.map((word, index) => {
    const duration = speechDuration * (weights[index] / totalWeight);
    const start = wordCursor;
    const end = Math.min(beatEnd, start + duration);
    wordCursor = end;
    return {text: word, start_seconds: start, end_seconds: end, index};
  });
}

const payload = {
  project_id: manifest.project_id,
  source: existsSync(alignmentPath) ? 'silence-aligned-estimate' : 'beat-duration-estimate',
  note: 'Word timing is deterministic fallback timing. A future Whisper adapter can replace this map without changing the compositor contract.',
  generated_at: new Date().toISOString(),
  beats: map,
};

const jsonPath = join(timingDir, 'word-timing.json');
await writeFile(jsonPath, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
await writeFile(runtimePath, `// Generated by src/prepare-timing.ts — do not edit manually.\nexport const runtimeTiming = ${JSON.stringify(map, null, 2)} as const;\n`, 'utf8');

console.log(`[timing] ${Object.keys(map).length} beats prepared; source=${payload.source}`);
console.log(`[timing] report: ${jsonPath}`);
