import {existsSync} from 'node:fs';
import {mkdir, readFile, writeFile} from 'node:fs/promises';
import {spawn} from 'node:child_process';

const input = process.argv[2] ?? 'examples/karna-short.json';
const output = process.argv[3] ?? `renders/${input.split('/').pop()?.replace(/\.json$/i, '') ?? 'mythic-short'}.mp4`;

await mkdir('renders', {recursive: true});

const run = (cmd: string, args: string[]) => new Promise<void>((resolve, reject) => {
  const child = spawn(cmd, args, {stdio: 'inherit'});
  child.on('error', reject);
  child.on('exit', (code) => code === 0 ? resolve() : reject(new Error(`${cmd} exited with ${code}`)));
});

if (!existsSync(input)) throw new Error(`Manifest not found: ${input}`);

await run('npx', ['tsx', 'src/cli.ts', 'validate', input]);
await run('npx', ['tsx', 'src/pipeline/prepare-project.ts', input]);
await run('npx', ['tsx', 'src/generate-assets.ts', input]);
await run('npx', ['tsx', 'src/normalize-assets.ts', input]);
if (process.env.REQUIRE_GENERATED_ASSETS === '1') {
  await run('npx', ['tsx', 'src/inspect-assets.ts', input]);
}
await run('npx', ['tsx', 'src/generate-voice.ts', input]);
if (process.env.REQUIRE_TTS === '1') {
  await run('npx', ['tsx', 'src/inspect-audio.ts', input]);
}
await run('npx', ['tsx', 'src/stage-assets.ts', input]);

const manifest = JSON.parse(await readFile(input, 'utf8'));
const runtimeSource = `// Generated by src/produce.ts — do not edit manually.\nexport const runtimeManifest = ${JSON.stringify(manifest, null, 2)} as const;\n`;
await writeFile('src/remotion/runtime-manifest.ts', runtimeSource, 'utf8');

await run('npx', ['remotion', 'render', 'src/remotion/index.ts', 'MythicShort', output]);
console.log(`DONE: ${output}`);
