import {existsSync} from 'node:fs';
import {copyFile, mkdir, writeFile} from 'node:fs/promises';
import {basename, join} from 'node:path';
import {readFile} from 'node:fs/promises';
import {projectPaths, ensureProjectPaths} from './pipeline/paths';
import {loadRegistry} from './pipeline/asset-registry';
import {buildAssetPlan} from './pipeline/asset-plan';
import type {ProductionManifest} from './pipeline/types';

const input = process.argv[2] ?? 'examples/karna-short.json';
const manifest = JSON.parse(await readFile(input, 'utf8')) as ProductionManifest;
const paths = projectPaths(manifest.project_id);
await ensureProjectPaths(paths);
const registry = await loadRegistry(paths, manifest.project_id);
const plan = buildAssetPlan(manifest);
const publicRoot = join('public', 'generated', manifest.project_id);
const publicAudioRoot = join('public', 'audio', manifest.project_id);
await mkdir(publicRoot, {recursive: true});
await mkdir(publicAudioRoot, {recursive: true});

const assets: Record<string, string> = {};
let staged = 0;
let skipped = 0;

for (const request of plan) {
  const record = registry.assets[request.id];
  if (!record?.path || !existsSync(record.path) || record.status !== 'ready') {
    skipped += 1;
    continue;
  }
  const filename = `${request.id.replaceAll('.', '_')}-${basename(record.path)}`;
  const destination = join(publicRoot, filename);
  await copyFile(record.path, destination);
  assets[request.id] = `/generated/${manifest.project_id}/${filename}`;
  staged += 1;
}

const mixPath = join('projects', manifest.project_id, 'audio', 'final-mix.wav');
let runtimeAudio: string | null = null;
if (existsSync(mixPath)) {
  const audioDestination = join(publicAudioRoot, 'final-mix.wav');
  await copyFile(mixPath, audioDestination);
  runtimeAudio = `/audio/${manifest.project_id}/final-mix.wav`;
}

// The real KATHAAYA emblem (public/brand/kathaaya-logo.png) is a fixed shared brand asset, not a
// per-project generated one — it may not have been placed on this machine yet. Checked here
// (Node, has fs) rather than in the compositor (bundled for the browser, no fs) so the compositor
// can degrade gracefully to the text wordmark instead of an Img tag pointed at a 404.
const brandLogoAvailable = existsSync(join('public', 'brand', 'kathaaya-logo.png'));

const runtimeSource = `// Generated by src/stage-assets.ts — do not edit manually.\nexport const runtimeAssets = ${JSON.stringify(assets, null, 2)} as const;\n`;
const audioSource = `// Generated by src/stage-assets.ts — do not edit manually.\nexport const runtimeAudio = ${JSON.stringify(runtimeAudio)} as string | null;\n`;
const brandSource = `// Generated by src/stage-assets.ts — do not edit manually.\nexport const brandLogoAvailable = ${JSON.stringify(brandLogoAvailable)} as boolean;\n`;
await writeFile('src/remotion/runtime-assets.ts', runtimeSource, 'utf8');
await writeFile('src/remotion/runtime-audio.ts', audioSource, 'utf8');
await writeFile('src/remotion/runtime-brand.ts', brandSource, 'utf8');
console.log(`Brand logo asset: ${brandLogoAvailable ? 'found' : 'MISSING (public/brand/kathaaya-logo.png) — falling back to text wordmark'}`);
await writeFile(join(paths.logs, 'staged-assets.json'), `${JSON.stringify({project_id: manifest.project_id, staged, skipped, assets, audio: runtimeAudio}, null, 2)}\n`, 'utf8');
console.log(`Staged assets: ${staged}; skipped: ${skipped}`);
console.log(`Final audio: ${runtimeAudio ?? 'none'}`);
console.log(`Runtime asset map: src/remotion/runtime-assets.ts`);
