import {existsSync} from 'node:fs';
import {copyFile, mkdir, writeFile} from 'node:fs/promises';
import {basename, join, relative} from 'node:path';
import {readFile} from 'node:fs/promises';
import {projectPaths, ensureProjectPaths} from './pipeline/paths';
import {loadRegistry} from './pipeline/asset-registry';
import {buildAssetPlan} from './pipeline/asset-plan';
import type {ProductionManifest} from './pipeline/types';

const input = process.argv[2] ?? 'examples/karna-short.json';
const manifest = JSON.parse(await readFile(input, 'utf8')) as ProductionManifest;
const paths = projectPaths(manifest.project_id);
await ensureProjectPaths(paths);
const registry = await loadRegistry(paths, manifest.project_id);
const plan = buildAssetPlan(manifest);
const publicRoot = join('public', 'generated', manifest.project_id);
await mkdir(publicRoot, {recursive: true});

const assets: Record<string, string> = {};
let staged = 0;
let skipped = 0;

for (const request of plan) {
  const record = registry.assets[request.id];
  if (!record?.path || !existsSync(record.path) || record.status !== 'ready') {
    skipped += 1;
    continue;
  }
  const filename = `${request.id.replaceAll('.', '_')}-${basename(record.path)}`;
  const destination = join(publicRoot, filename);
  await copyFile(record.path, destination);
  assets[request.id] = `/generated/${manifest.project_id}/${filename}`;
  staged += 1;
}

const runtimeSource = `// Generated by src/stage-assets.ts — do not edit manually.\nexport const runtimeAssets = ${JSON.stringify(assets, null, 2)} as const;\n`;
await writeFile('src/remotion/runtime-assets.ts', runtimeSource, 'utf8');
await writeFile(join(paths.logs, 'staged-assets.json'), `${JSON.stringify({project_id: manifest.project_id, staged, skipped, assets}, null, 2)}\n`, 'utf8');
console.log(`Staged assets: ${staged}; skipped: ${skipped}`);
console.log(`Runtime asset map: src/remotion/runtime-assets.ts`);
